[package]
name = "solid-web"
version = "0.1.0"
authors = ["Sam Vervaeck <vervaeck.sam@skynet.be>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.37", features = ["Storage"] } 

